name: Build Linux

on: [pull_request, push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get Submodules
      run: git submodule update --init
    
    - name: Setup CMake
      run: cmake ${{github.workspace}}/test/CMakeLists.txt -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      
    - name: Build
      run: cmake --build ${{github.workspace}}/test/. --config ${{env.BUILD_TYPE}}
