name: Test Linux

on: [pull_request, push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get Submodules
      run: git submodule update --init
      working-directory: ${{github.workspace}}
    
    - name: Setup CMake
      run: cmake CMakeLists.txt
      working-directory: ${{github.workspace}}/test
      
    - name: Build
      run: cmake --build . --config ${{env.BUILD_TYPE}}
      working-directory: ${{github.workspace}}/test

    - name: Test
      run: ctest -V .
      working-directory: ${{github.workspace}}/test
